In [4]:
import pandas as pd
import time

In [6]:
start_time = time.time()
def main():
    def dc_split(line):
        A = line.split(',')
        date = A[2]
        year = date[0:4]
        cost = float(A[7])
        dcv = [year,cost]
        return dcv

    def cpy(co,data1):
        df = []
        data = []
        co = str(co)
        with open(f"{co}.csv") as f:
            for line in f:
                a = dc_split(line)
                data.append(a)
        for year in range(2015,2020):
            closes = []
            close_changes = []
            for i in range(len(data)):
                if str(year) == data[i][0]:
                    close = data[i][1]
                    closes.append(close)
            for i in range(len(closes)-1):
                close_change = closes[i+1] - closes[i]
                close_changes.append(close_change)
            change_min = min(close_changes)
            df.append(change_min)
        data1.append(df)
    data1=[]
    companies = [
        "ALRS",
        "GAZP",
        "CHMF",
        "ADR.FIVE",
        "GMKN",
        "LKOH",
        "MGNT",
        "MTSS",
        "NLMK",
        "NVTK",
        "ROSN",
        "SBER",
        "SNGS",
        "TATN",
        "YNDX"
    ]
    for co in companies:
        cpy(co,data1)
    df = pd.DataFrame(data=data1, index = companies, columns = range(2015,2020))
    return df

main()
print("--- %s seconds ---" % (time.time() - start_time))
main()

--- 0.07698607444763184 seconds ---

              2015    2016    2017     2018    2019
ALRS        -5.490   -3.50   -6.66    -7.11   -3.02
GAZP        -7.110   -6.36   -5.17    -7.02  -17.82
CHMF       -26.500  -57.00  -37.00   -74.80  -61.40
ADR.FIVE    -1.450   -2.14   -2.10    -3.11   -1.46
GMKN      -676.000 -414.00 -445.00 -1563.00 -708.00
LKOH      -115.000 -125.50 -129.00  -319.00 -201.50
MGNT     -1070.000 -755.00 -895.00  -631.00 -131.00
MTSS       -21.900  -12.30  -28.70   -20.50  -16.35
NLMK        -4.000   -5.60   -6.40   -13.62  -10.80
NVTK       -25.800  -32.40  -31.10   -51.40  -34.40
ROSN       -12.050  -14.35  -13.10   -23.55  -14.00
SBER        -6.000   -7.20   -6.29   -43.76  -13.11
SNGS        -1.625   -1.72   -3.13    -1.56   -1.98
TATN       -22.850  -23.30  -22.15   -45.50  -35.10
YNDX       -84.000 -125.00 -134.00  -445.00 -429.00